var hardWordsList = [
    "phlegm",
    "neonatologist",
    "urologist"];
//hard words list is not very good :(
var foodBrandWordsList = [
    "cocacola",
    "ritz",
    "hobnob",
    "baskin robbins",
    "cadbury",
    "carnation",
    "alpro",
    "nesquik",
    "maypo",
    "del monte",
    "heinz",
    "contadia",
    "cheetos",
    "cheeselets",
    "doritos",
    "fritos",
    "cornnuts",
    "kettle",
    "kurkure",
    "kp nuts",
    "horizon",
    "borden",
    "ambrosia",
    "haagen-dazs",
    "in-n-out",
    "magnum",
    "butterball",
    "gwaltney",
    "jennie-o",
    "branston",
    "dufrais",
    "tiptree",
    "rafhan",
    "nutella",
    "skippy",
    "conimex",
    "cauldron",
    "continental",
    "kabs",
    "peperami",
    "pocky",
    "slim jim",
    "campbells",
    "cup noodles",
    "kraft dinner",
    "snickers"];
var commonBrandWordslist = [
    "nike",
    "addidas",
    "sphero",
    "wallmart",
    "mcdonalds",
    "starbucks",
    "lego",
    "apple",
    "lenovo",
    "columbia",
    "acer",
    "samsung",
    "alienware",
    "target",
    "trader joe's",
    "spotify",
    "amazon",
    "google",
    "rei"];
var carBrandWordslist = [
    "toyota",
    "honda",
    "ford",
    "peugot",
    "ferrari",
    "mitsubishi",
    "bmw",
    "volkswagen",
    "porche",
    "jaguar",
    "tesla",
    "buggati",
    "rolls-royce",
    "lamborgini",
    "lincoln",
    "jeep",
    "chevrolet",
    "fiat",
    "chrysler"];
var videogameWordsList = [
    "atari",
    "nintendo",
    "minecraft",
    "breakout",
    "zelda",
    "super smash bros",
    "mariokart",
    "destiny",
    "halo",
    "fortnite",
    "xbox",
    "pacman",
    "pokemon",
    "fallout",
    "mario",
    "assassins creed",
    "battlefield",
    "call of duty",
    "god of war",
    "diablo",
    "skyrim",
    "doom",
    "red dead redemption",
    "fifa",
    "pong",
    "tetris",
    "space invaders",
    "rocket league",
    "portal",
    "sonic",
    "league of legends",
    "hitman",
    "far cry",
    "mass effect"];